//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterPdvCoronel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_VENDA
    {
        public int ID { get; set; }
        public int COD_VENDA { get; set; }
        public int COD_PRODUTO { get; set; }
        public decimal VAL_UNITARIO { get; set; }
        public int QUANTIDADE { get; set; }
    
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual VENDA VENDA { get; set; }
    }
}
