//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterPdvCoronel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGAMENTO
    {
        public int CODIGO { get; set; }
        public string TIPO_PG { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<decimal> TROCO { get; set; }
        public int COD_VENDA { get; set; }
    
        public virtual VENDA VENDA { get; set; }
    }
}
