//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterPdvCoronel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.ITEM_VENDA = new HashSet<ITEM_VENDA>();
        }
    
        public int CODIGO { get; set; }
        public string COD_BARRA { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public int QTD_ESTOQUE { get; set; }
        public decimal VALOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_VENDA> ITEM_VENDA { get; set; }
    }
}
