//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterPdvCoronel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int CODIGO { get; set; }
        public string NOME { get; set; }
        public string SOBRENOME { get; set; }
        public string CPF { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public string STATUS { get; set; }
        public int NIVEL { get; set; }
    }
}
